### ISSUE TITLE
Help needed to prepare dataset.

### ISSUE THREAD

**Issue by purvang3** [researchmm/LightTrack#2]
downloaded from https://www.votchallenge.net/vot2019/dataset.html

VOT2019 dataset preview

but did not have list.txt

FileNotFoundError: [Errno 2] No such file or directory: 'LightTrack/lib/utils/../../dataset/VOT2019/list.txt'

**Comment by MasterBin-IIAU** [comment]
Hi, sorry for the late reply. Please download the VOT2019 dataset using the official [VOT Toolkit](https://votchallenge.net/howto/). Thanks.

**Comment by TCBocean** [comment]
list.txt is the name of each folder in VOT2019, similar to the following:
```
agility
ants1
ball2
ball3
basketball
birds1
bolt1
……
```
You can write a python script directly to generate it.

**Comment by purvang3** [comment]
Thanks @MasterBin-IIAU and @TCBocean. working now.
