### ISSUE TITLE
Why is a tracker based on offline tracking so robust?

### ISSUE THREAD

**Issue by makalo** [researchmm/LightTrack#3]
The paper is similar to siamfc++, except that the network layer is changed. Why is it so robust that it is better than online updates, such as dimp. How does this offline tracking tracker distinguish distractor?

**Comment by MasterBin-IIAU** [comment]
Hi, thanks for your interest to our work :)
I think the reason why LightTrack achieves good performance is that the searched architecture is more suitable to the object tracking task and the learnt features are more powerful(discriminative) than previous trackers. 
However, like other offline trackers, it is not easy for LightTrack to distinguish the target and similar distractors.

**Comment by jcyhcs** [comment]
@MasterBin-IIAU @makalo 
HI,professor:
is lighttrack an offline tracking algorithm? that means it can not use in the scene which need tracking an object in a live camera?
please help!

**Comment by MasterBin-IIAU** [comment]
@jcyhcs Hi, here "offline" means "without any update of model parameters during tracking". LightTrack is still a causal tracker, which predicts tracking results of the current frame only based on the information from previous frames. So it can still be applied in tracking scenarios like live cameras.
