### ISSUE TITLE
About the pixel_corr_mat method

### ISSUE THREAD

**Issue by TCBocean** [researchmm/LightTrack#5]
I noticed that the method of cross-correlation is different from the general siam tracker. In the code, the matrix multiplication method is used as the pixel cross-correlation, and the channel separable convolution method is generally used as the channel cross-correlation. What are the advantages of using pixel correlation?
Looking forward to your reply, thank you very much!

**Comment by MasterBin-IIAU** [comment]
Hi, thanks for your interest to our work :)
LightTrack uses pixel-wise correlation to fuse the features of the template and the search region. 
More details about the difference between the pixel-wise correlation and the depth-wise correlation can be found in the paper [AlphaRefine](https://arxiv.org/abs/2012.06815)'s section 3.2
Thanks

**Comment by TCBocean** [comment]
Thank you for your reply, it is very helpful to me.
